### PR TITLE
Portuguese European pt-PT translation complete

### PR DESCRIPTION
**Pull request by Ricardo-Simoes**
Complete 100% Portuguese European pt-PT (Portugal) translation for v5.4.2

### CODE REVIEW

**Comment by Ricardo-Simoes** [comment]
Sorry I think I closed this pull request by accident

**Comment by Taiko2k** [comment]
Looks alight, just a couple of issues where unfortunately as it is there's not enough space for the text. Would be convenient if you could shorten these somehow.

Two here:
Screenshot from 2020-04-03 12-03-53

One here:
Screenshot from 2020-04-03 12-04-08

This one is a little close:
Screenshot from 2020-04-03 12-22-17


I'm going to truncate these as shown, but you could optionally shorten them if you can.

Screenshot from 2020-04-03 12-14-32

**Comment by Ricardo-Simoes** [comment]
> Looks alight, just a couple of issues where unfortunately as it is there's not enough space for the text. Would be convenient if you could shorten these somehow.

Ok, I've done as you suggested, can you please check if everything is ok now?

**Comment by Taiko2k** [comment]
Looks good. This should be available with the upcoming v5.4.3 release. At that time, let me know if its not working or if there's any issues.

**Pull request merged**
