### PR TITLE
Create Sweet.ttheme

### PR DESCRIPTION
**Pull request by the-root-user**
A rather minimalist theme

### CODE REVIEW

**Comment by the-root-user** [comment]
Preview:
Screenshot-23

**Comment by Taiko2k** [comment]
Looks pretty decent to me. Just two things come to mind:

1. Maybe the track artist should have a colour highlight as well, not just the title?
2. I'm not sure the name is exactly fitting to the theme. How about the name "Ash"?

What are your thoughts?

**Comment by the-root-user** [comment]
Thanks. I don't want the Artist highlight actually. I even wanted to have the listing like "Title Artist" but don't know yet how to do that.
"Ash" is a lovely name.

**Comment by the-root-user** [comment]
Though, (on my side) I changed blur from 9 to 15 and it looks cool (also in above snapshot). With 9, things seemed a bit messy. If you have any plans ... :)

**Comment by Taiko2k** [comment]
> I even wanted to have the listing like "Title Artist" but don't know yet how to do that.

You can sort of do this in the 'columns' view where you can re-order the columns. But the standard view is hard coded.

**Comment by the-root-user** [comment]
You forgot to rename? or decided to keep.
OR should I pull another request

**Comment by Taiko2k** [comment]
Ill do it

**Pull request merged**
